dist: xenial
language: python

stages:
  - test

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry
    - $HOME/boost_1_69_0

jobs:
  fast_finish: true
  include:
    - python: 3.6

install:
  - pushd $HOME;
    if [ ! -d boost_1_69_0/boost ];
    then 
      curl -sSL https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz | tar zx;
    fi;
    popd
  - export CMAKE_PREFIX_PATH=$HOME/boost_1_69_0
  - mkdir cppbuild
  - cd cppbuild
  - cmake ../cpp -DPYTHON_EXECUTABLE=$(which python3)
  - make
  - cd ..
  - pip install pip -U
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script: 
  - poetry run pytest
  - cd cppbuild
  - make test
